//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class StaticModules_SqliteDbManageWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(StaticModules.SqliteDbManage), typeof(System.Object));
		L.RegFunction("GetInstance", GetInstance);
		L.RegFunction("GetConfigDb", GetConfigDb);
		L.RegFunction("GetServerDb", GetServerDb);
		L.RegFunction("GetCacheDb", GetCacheDb);
		L.RegFunction("New", _CreateStaticModules_SqliteDbManage);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateStaticModules_SqliteDbManage(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				StaticModules.SqliteDbManage obj = new StaticModules.SqliteDbManage();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: StaticModules.SqliteDbManage.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			StaticModules.SqliteDbManage o = StaticModules.SqliteDbManage.GetInstance();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetConfigDb(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			StaticModules.SqliteDbManage obj = (StaticModules.SqliteDbManage)ToLua.CheckObject(L, 1, typeof(StaticModules.SqliteDbManage));
			SqliteDbHelper o = obj.GetConfigDb();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetServerDb(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			StaticModules.SqliteDbManage obj = (StaticModules.SqliteDbManage)ToLua.CheckObject(L, 1, typeof(StaticModules.SqliteDbManage));
			SqliteDbHelper o = obj.GetServerDb();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCacheDb(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			StaticModules.SqliteDbManage obj = (StaticModules.SqliteDbManage)ToLua.CheckObject(L, 1, typeof(StaticModules.SqliteDbManage));
			SqliteDbHelper o = obj.GetCacheDb();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

