//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class StaticModules_ResourceManageWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(StaticModules.ResourceManage), typeof(System.Object));
		L.RegFunction("GetInstance", GetInstance);
		L.RegFunction("Load", Load);
		L.RegFunction("New", _CreateStaticModules_ResourceManage);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateStaticModules_ResourceManage(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				StaticModules.ResourceManage obj = new StaticModules.ResourceManage();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: StaticModules.ResourceManage.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			StaticModules.ResourceManage o = StaticModules.ResourceManage.GetInstance();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Load(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			StaticModules.ResourceManage obj = (StaticModules.ResourceManage)ToLua.CheckObject(L, 1, typeof(StaticModules.ResourceManage));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.Object o = obj.Load(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

