local Const={};
local this=Const;

this.SCENE_MAIN="Main";
this.SCENE_LOGIN="Login";

this.EVENT_STARTGAME="EVENT_STARTGAME";
this.EVENT_UPDATEGAME="EVENT_UPDATEGAME";
this.EVENT_UPDATEGAME_YES="EVENT_UPDATEGAME_YES";
this.EVENT_UPDATEGAME_NO="EVENT_UPDATEGAME_NO";

return this;
